sudo: false
language: python
python:
  - 2.7
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:20.3
install:
  - pip install sphinx sphinx_rtd_theme
script: "./build_couchdb.sh"
before_deploy: tar -zcf couchdb.tar.gz couchdb/rel
deploy:
  provider: releases
  api_key:
    secure: VVJSH971P1KWIddqiff6vNRuJKTjGnUUsgl/Ox9Wp86ScFkK31JtDm9I5Kg/er8DVJqyfGaUKICn0ecS9RR0YhXvsL6wqMsfJxBmAlmdvv7xIFrygWbspFica0v15Y7x/StfBHInBiQcUki34KfFbRNyjbbWmB+LCXLftW70Ecw=
  file: couchdb.tar.gz
  skip_cleanup: true
  on:
    repo: davedoesdev/build-couchdb-travis
    tags: true
    all_branches: true
