sudo: false
language: c
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:20.3
script: ./build_couchdb.sh
before_deploy: tar -zcf couchdb.tar.gz couchdb/rel
deploy:
  provider: releases
  api_key:
    secure: UMcd90RGzcS2jp5UmdYNsLS9cWxr2ZBSV/du/5xTbQQfEmicr74PFevpxrhOfJv0QCLdCBdA0hViGx1PeJJ3nW/nF0WqBnVBnyjlAYTwoXF01TukviC8bYdU2HKPKbrABv6Wnfo0oyazvUq4j6ZvMJUIUZ8PP3DJgSwYrjOE9oI=
  file: couchdb.tar.gz
  skip_cleanup: true
  on:
    repo: davedoesdev/build-couchdb-travis
    tags: true
    all_branches: true
