dist: bionic
language: python
python:
  - 2.7
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:22.0.7-1
install:
  - pip install sphinx sphinx_rtd_theme
script: "./build_couchdb.sh"
before_deploy:
  - tar -zcf couchdb.tar.gz couchdb/rel
  - $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" --iv "$encrypted_XXXXXXXXXXXX_iv" --path-encrypted-key "travis_key.enc"
deploy:
  provider: releases
  file: couchdb.tar.gz
  skip_cleanup: true
  on:
    repo: davedoesdev/build-couchdb-travis
    tags: true
    all_branches: true
