dist: bionic
language: python
python:
  - 2.7
addons:
  apt:
    sources:
      - sourceline: deb https://binaries.erlang-solutions.com/debian bionic contrib
        key_url: https://binaries.erlang-solutions.com/debian/erlang_solutions.asc
    packages:
      - esl-erlang=1:22.2.3-1
install:
  - pip install sphinx sphinx_rtd_theme
script: "./build_couchdb.sh"
before_deploy:
  - tar -zcf couchdb.tar.gz couchdb/rel
deploy:
  provider: releases
  api_key:
    secure: T/n9PIfOj5JkkymnlzumyppVVbRPBKh04TxSRezcg9+putoX9aIRAixqh058IOD1xlxpizc4x1qM3O5gTb2Ysvw7CjXTDW/0psSEFejq+eGu6KOZr0PqHYwg0kAiaJleHdB6I7BGmAJ5xJoXG/++fRgH0Y8MY6YkJ7KSx0lfsU8=
  file: couchdb.tar.gz
  skip_cleanup: true
  on:
    repo: davedoesdev/build-couchdb-travis
    tags: true
    all_branches: true
