name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install python3-sphinx python3-sphinx-rtd-theme python2

      - name: Set OTP
        uses: erlef/setup-beam@caa49b06584b5d1827ac6767470ed43aa150e9bb
        with:
          otp-version: 24.3.4

      - name: where is include dir 
        run: |
          export
          locate eurl_nif.h

      - name: Set Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build CouchDB
        run: ./build_couchdb.sh

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          mv couchdb/rel artifacts/couchdb

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: couchdb
          path: artifacts

      - name: Prepare release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tar -zcf couchdb.tar.gz -C artifacts couchdb

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: couchdb.tar.gz
