name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install python3-sphinx python3-sphinx-rtd-theme

      - name: Build CouchDB
        run: ./build_couchdb.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: couchdb
          path: couchdb/rel
