name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install python3-sphinx python3-sphinx-rtd-theme

      - name: Build CouchDB
        run: ./build_couchdb.sh

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          mv couchdb/rel artifacts/couchdb

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: couchdb
          path: artifacts

      - name: Prepare release
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -C artifacts -zcf couchdb.tar.gz couchdb

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/couchdb.tar.gz
